spring:
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:61157/pe
    username: admin
    password: admin
grpc:
  port: 9093
  enable-reflection: true