[versions]
spring-boot = "3.1.4"

[plugins]
spring = { id = "org.springframework.boot", version.ref = "spring-boot" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }

[libraries]
spring-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "spring-boot" }
spring-data = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }

spring-grpc = { module = "io.github.lognet:grpc-spring-boot-starter", version = "5.1.0" }

liquibase = { module = "org.liquibase:liquibase-core", version = "4.24.0" }

javax-annotation = { module = "javax.annotation:javax.annotation-api", version = "1.3.2" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.26" }
postgresql-driver = { module = "org.postgresql:postgresql", version = "42.6.0" }

protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version = "3.23.0" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version = "1.54.1" }
grpc-stub = { module = "io.grpc:grpc-stub", version = "1.55.1" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version = "3.23.0" }

#Test libraries
testcontainers-core = { module = "org.testcontainers:testcontainers", version = "1.19.1" }
jupiter = { module = "org.junit.jupiter:junit-jupiter", version = "5.10.0" }
