server:
  port: 8084
spring:
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:61156/origination
    username: admin
    password: admin
grpc:
  port: 9094
  enable-reflection: true
